import { useEffect, useState } from 'react'
import { projectsApi, findingsApi, assetsApi } from '@/services/api'
import type { Project, Finding, Asset } from '@/types'
import { FileText, Download, Copy, Check, ClipboardCopy } from 'lucide-react'
import { cn } from '@/lib/utils'
import toast from 'react-hot-toast'

export default function ReportsPage() {
  const [projects, setProjects] = useState<Project[]>([])
  const [selectedProject, setSelectedProject] = useState<number | null>(null)
  const [findings, setFindings] = useState<Finding[]>([])
  const [assets, setAssets] = useState<Asset[]>([])
  const [generating, setGenerating] = useState(false)
  const [report, setReport] = useState<string>('')
  const [format, setFormat] = useState<'markdown' | 'json'>('markdown')
  const [copied, setCopied] = useState(false)

  useEffect(() => {
    projectsApi.list().then(p => {
      setProjects(p)
      if (p.length > 0) setSelectedProject(p[0].id)
    })
  }, [])

  useEffect(() => {
    if (!selectedProject) return
    Promise.all([
      findingsApi.list(selectedProject).then(setFindings),
      assetsApi.list(selectedProject).then(setAssets),
    ])
  }, [selectedProject])

  const generateReport = () => {
    setGenerating(true)
    const project = projects.find(p => p.id === selectedProject)
    if (!project) { setGenerating(false); return }

    if (format === 'markdown') {
      const now = new Date().toISOString().split('T')[0]
      const criticalFindings = findings.filter(f => f.severity === 'critical')
      const highFindings = findings.filter(f => f.severity === 'high')
      const mediumFindings = findings.filter(f => f.severity === 'medium')
      const lowFindings = findings.filter(f => f.severity === 'low')
      const infoFindings = findings.filter(f => f.severity === 'info')

      const md = `# Security Assessment Report

**Project:** ${project.name}
**Target:** ${project.targets?.map(t => t.target).join(', ') || 'N/A'}
**Date:** ${now}
**Generated by:** PenAgent

---

## Executive Summary

This report presents the findings from an authorized security assessment of **${project.targets?.map(t => t.target).join(', ')}**. The assessment discovered **${assets.length} assets** and identified **${findings.length} potential vulnerabilities** across the target infrastructure.

| Severity | Count |
|----------|-------|
| Critical | ${criticalFindings.length} |
| High | ${highFindings.length} |
| Medium | ${mediumFindings.length} |
| Low | ${lowFindings.length} |
| Info | ${infoFindings.length} |

---

## Scope

### Included
${project.scope_rules?.filter(r => r.rule_type === 'include').map(r => `- \`${r.pattern}\``).join('\n') || '- Not specified'}

### Excluded
${project.scope_rules?.filter(r => r.rule_type === 'exclude').map(r => `- \`${r.pattern}\``).join('\n') || '- None'}

---

## Methodology

The following automated reconnaissance pipeline was used:
1. **Subdomain Enumeration** — Passive discovery of subdomains
2. **HTTP Probing** — Identifying live web services
3. **Web Crawling** — Discovering endpoints and parameters
4. **Vulnerability Scanning** — Automated vulnerability detection via Nuclei
5. **AI Analysis** — Local LLM-assisted finding triage and prioritization

---

## Assets Discovered

- **Total Assets:** ${assets.length}
- **Subdomains:** ${project.stats?.subdomains ?? 0}
- **Live Hosts:** ${project.stats?.live_hosts ?? 0}
- **URLs:** ${project.stats?.urls ?? 0}
- **Parameters:** ${project.stats?.parameters ?? 0}

---

## Findings

${findings.length === 0 ? '*No findings were discovered during this assessment.*\n' : ''}
${findings.map((f, i) => `### ${i + 1}. ${f.title}

| Field | Value |
|-------|-------|
| **Severity** | ${f.severity.toUpperCase()} |
| **Confidence** | ${f.confidence} |
| **Status** | ${f.status} |
| **Target** | \`${f.target_url || 'N/A'}\` |
${f.http_method ? `| **Method** | ${f.http_method} |` : ''}
${f.parameter ? `| **Parameter** | \`${f.parameter}\` |` : ''}
${f.detection_source ? `| **Source** | ${f.detection_source} |` : ''}

${f.description ? `**Description:** ${f.description}\n` : ''}
${f.evidence ? `**Evidence:**\n\`\`\`\n${f.evidence}\n\`\`\`\n` : ''}
${f.impact ? `**Impact:** ${f.impact}\n` : ''}
${f.remediation ? `**Remediation:** ${f.remediation}\n` : ''}
---
`).join('\n')}

## Disclaimer

This assessment was performed under authorized bug bounty program scope. All testing was conducted in accordance with the program's rules of engagement. Findings are presented as-is for review and should be validated manually before submission.

---
*Report generated by PenAgent on ${now}*
`
      setReport(md)
    } else {
      const jsonReport = {
        report_type: 'security_assessment',
        project: {
          name: project.name,
          targets: project.targets?.map(t => t.target),
          scope_includes: project.scope_rules?.filter(r => r.rule_type === 'include').map(r => r.pattern),
          scope_excludes: project.scope_rules?.filter(r => r.rule_type === 'exclude').map(r => r.pattern),
        },
        generated_at: new Date().toISOString(),
        summary: {
          total_assets: assets.length,
          total_findings: findings.length,
          by_severity: {
            critical: findings.filter(f => f.severity === 'critical').length,
            high: findings.filter(f => f.severity === 'high').length,
            medium: findings.filter(f => f.severity === 'medium').length,
            low: findings.filter(f => f.severity === 'low').length,
            info: findings.filter(f => f.severity === 'info').length,
          },
        },
        findings: findings.map(f => ({
          id: f.id, title: f.title, severity: f.severity, confidence: f.confidence,
          status: f.status, target_url: f.target_url, http_method: f.http_method,
          parameter: f.parameter, detection_source: f.detection_source,
          description: f.description, evidence: f.evidence, impact: f.impact,
          remediation: f.remediation, created_at: f.created_at,
        })),
      }
      setReport(JSON.stringify(jsonReport, null, 2))
    }
    setGenerating(false)
  }

  const handleCopy = () => {
    navigator.clipboard.writeText(report)
    setCopied(true)
    toast.success('Report copied to clipboard')
    setTimeout(() => setCopied(false), 2000)
  }

  const handleDownload = () => {
    const ext = format === 'markdown' ? 'md' : 'json'
    const mime = format === 'markdown' ? 'text/markdown' : 'application/json'
    const blob = new Blob([report], { type: mime })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `penagent-report-${new Date().toISOString().split('T')[0]}.${ext}`
    a.click()
    URL.revokeObjectURL(url)
    toast.success('Report downloaded')
  }

  return (
    <div className="space-y-6 h-full flex flex-col">
      <div className="flex items-center justify-between shrink-0">
        <div>
          <h1 className="text-2xl font-bold">Reports</h1>
          <p className="text-sm text-muted-foreground mt-1">Generate professional bug bounty reports</p>
        </div>
        <select value={selectedProject ?? ''} onChange={e => setSelectedProject(Number(e.target.value))}
          className="bg-secondary border border-border rounded-md px-3 py-2 text-sm w-64">
          {projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}
        </select>
      </div>

      {/* Controls */}
      <div className="bg-card border border-border rounded-lg p-4 flex items-center justify-between shrink-0">
        <div className="flex items-center space-x-4">
          <div className="flex items-center space-x-2 bg-secondary rounded-md p-0.5">
            <button onClick={() => setFormat('markdown')}
              className={cn('px-3 py-1.5 text-sm rounded-md transition-colors', format === 'markdown' ? 'bg-primary text-primary-foreground' : 'text-muted-foreground')}>
              Markdown
            </button>
            <button onClick={() => setFormat('json')}
              className={cn('px-3 py-1.5 text-sm rounded-md transition-colors', format === 'json' ? 'bg-primary text-primary-foreground' : 'text-muted-foreground')}>
              JSON
            </button>
          </div>
          <span className="text-xs text-muted-foreground">
            {findings.length} findings · {assets.length} assets
          </span>
        </div>
        <div className="flex items-center space-x-2">
          <button onClick={generateReport} disabled={generating || !selectedProject}
            className="flex items-center space-x-2 px-4 py-2 bg-blue-600 text-white rounded-md text-sm font-medium hover:bg-blue-700 disabled:opacity-50">
            <FileText className="h-4 w-4" />
            <span>{generating ? 'Generating...' : 'Generate Report'}</span>
          </button>
          {report && (
            <>
              <button onClick={handleCopy}
                className="flex items-center space-x-2 px-3 py-2 bg-secondary text-secondary-foreground border border-border rounded-md text-sm hover:bg-secondary/80">
                {copied ? <Check className="h-4 w-4 text-green-400" /> : <ClipboardCopy className="h-4 w-4" />}
                <span>{copied ? 'Copied' : 'Copy'}</span>
              </button>
              <button onClick={handleDownload}
                className="flex items-center space-x-2 px-3 py-2 bg-secondary text-secondary-foreground border border-border rounded-md text-sm hover:bg-secondary/80">
                <Download className="h-4 w-4" />
                <span>Download</span>
              </button>
            </>
          )}
        </div>
      </div>

      {/* Report Output */}
      <div className="bg-[#0d1117] border border-border rounded-lg flex-1 overflow-hidden flex flex-col">
        {report ? (
          <div className="flex-1 overflow-auto p-6">
            <pre className="whitespace-pre-wrap text-sm font-mono text-gray-300 leading-relaxed">{report}</pre>
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center flex-1 text-muted-foreground space-y-4">
            <FileText className="h-16 w-16 opacity-20" />
            <div className="text-center">
              <p className="font-medium">No report generated yet</p>
              <p className="text-xs mt-1">Select a project and click "Generate Report" to create a professional bug bounty report.</p>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
